# Import theme colors
include ~/.config/kitty/kitty-matugen-colors.conf


font_family SF Mono
font_size 10

enable_audio_bell no

shell zsh

cursor_shape beam
cursor_trail 10
cursor_trail_decay 0.1 0.5
cursor_trail_start_threshold 0


remember_window_size no
window_padding_width 18

background_opacity            0.90
scrollbar_handle_opacity      0.10
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0

sync_to_monitor yes

# Copy on Ctrl+C (only if there is a selection)
map ctrl+c copy_and_clear_or_interrupt
copy_on_select yes

# Paste on Ctrl+V
map ctrl+v paste_from_clipboard

# Ctrl + Arrow Keys to move by words
map ctrl+left send_text all \x1bb
map ctrl+right send_text all \x1bf

# Ctrl + Backspace behind the cursor
map ctrl+backspace send_text all \x17

# =========================================================
# Browser-like Tab and Window Shortcuts
# =========================================================

# --- TAB CREATION ---
# Open a new tab (inheriting the current working directory)
map ctrl+t launch --cwd=current --type=tab

# Undo close tab (Reopen the last closed tab)
map ctrl+shift+t reopen_tab

# --- TAB & WINDOW DESTRUCTION ---
# Close the current tab
map ctrl+w close_tab

# Close the entire OS Window (Closes all tabs inside it)
map ctrl+shift+w close_os_window

# --- NAVIGATION ---
# Navigate tabs sequentially
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# Jump straight to specific tabs (1-9)
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# Open a brand new OS window
map ctrl+n new_os_window

